name = "GregTech Odyssey"
version = "0.0.3-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "041869eeb9b5e48828388ef8da9c387771e12d1dfd39b31724bf40911ae6bba4"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
